[build]
  # Default settings
  command = "npm run build"
  publish = "dist"  # Default build directory, adjust if needed

[[build.contexts.deploy-preview]]
  command = "npm run build"
  publish = "dist"

# Configuration for web1
[[plugins]]
  package = "@netlify/plugin-monorepo"

[[redirects]]
  from = "/web1"
  to = "/web1/index.html"
  status = 200

# Configuration for web2
[[plugins]]
  package = "@netlify/plugin-monorepo"

[[redirects]]
  from = "/web2"
  to = "/web2/index.html"
  status = 200


# Index.html Redirect
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
