[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/web1"
  to = "/web1/index.html"
  status = 200

[[redirects]]
  from = "/web2"
  to = "/web2/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
