[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-monorepo"

[[redirects]]
  from = "/web1"
  to = "/web1/index.html"
  status = 200

[[redirects]]
  from = "/web2"
  to = "/web2/index.html"
  status = 200


[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
